Emcee:
  auto_correlations:
    change_threshold: 0.01
    check_for_convergence: true
    check_size: 100
    required_length: 50
  initialize:
    ball_lower_limit: 0.49
    ball_upper_limit: 0.51
    method: prior
  parallel:
    number_of_cores: 1
  printing:
    silence: false
  run:
    nsteps: 2000
  search:
    nwalkers: 50
  updates:
    iterations_per_update: 2500
    log_every_update: 1
    model_results_every_update: 1
    remove_state_files_at_end: true
    visualize_every_update: 1
Zeus:
  auto_correlations:
    change_threshold: 0.01
    check_for_convergence: true
    check_size: 100
    required_length: 50
  initialize:
    ball_lower_limit: 0.49
    ball_upper_limit: 0.51
    method: prior
  parallel:
    number_of_cores: 1
  printing:
    silence: false
  run:
    check_walkers: true
    light_mode: false
    maxiter: 10000
    maxsteps: 10000
    mu: 1.0
    nsteps: 2000
    patience: 5
    shuffle_ensemble: true
    tolerance: 0.05
    tune: true
    vectorize: false
  search:
    nwalkers: 50
  updates:
    iterations_per_update: 500
    remove_state_files_at_end: true