Drawer:
  initialize:
    ball_lower_limit: 0.49
    ball_upper_limit: 0.51
    method: prior
  printing:
    silence: false
  search:
    total_draws: 10
LBFGS:
  initialize:
    ball_lower_limit: 0.49
    ball_upper_limit: 0.51
    method: prior
  options:
    disp: false
    eps: 1.0e-08
    ftol: 2.220446049250313e-09
    gtol: 1.0e-05
    iprint: -1.0
    maxcor: 10
    maxfun: 15000
    maxiter: 15000
    maxls: 20
  printing:
    silence: false
  search:
    tol: null
PySwarmsGlobal:
  initialize:
    ball_lower_limit: 0.49
    ball_upper_limit: 0.51
    method: prior
  parallel:
    number_of_cores: 1
  printing:
    silence: false
  run:
    iters: 2000
  search:
    cognitive: 0.1
    ftol: -.inf
    inertia: 0.3
    n_particles: 50
    social: 0.2
PySwarmsLocal:
  initialize:
    ball_lower_limit: 0.49
    ball_upper_limit: 0.51
    method: prior
  parallel:
    number_of_cores: 1
  printing:
    silence: false
  run:
    iters: 2000
  search:
    cognitive: 0.1
    ftol: -.inf
    inertia: 0.3
    minkowski_p_norm: 2
    n_particles: 50
    number_of_k_neighbors: 3
    social: 0.2
