DynestyDynamic:
  initialize:
    method: prior
  parallel:
    number_of_cores: 4
  printing:
    silence: false
  run:
    dlogz_init: 0.01
    logl_max_init: .inf
    maxcall: null
    maxcall_init: null
    maxiter: null
    maxiter_init: null
    nlive_init: 5
  search:
    bootstrap: 1
    bound: balls
    enlarge: 2
    facc: 0.6
    fmove: 0.8
    logl_max: .inf
    max_move: 101
    sample: rwalk
    slices: 6
    update_interval: 2.0
    walks: 26
  updates:
    iterations_per_update: 501
    log_every_update: 1
    model_results_every_update: 1
    remove_state_files_at_end: true
    visualize_every_update: 1
DynestyStatic:
  initialize:
    method: prior
  parallel:
    force_x1_cpu: false
    number_of_cores: 1
  printing:
    silence: true
  run:
    dlogz: null
    logl_max: .inf
    maxcall: null
    maxiter: null
  search:
    bootstrap: null
    bound: multi
    enlarge: null
    facc: 0.5
    first_update: null
    fmove: 0.9
    max_move: 100
    nlive: 150
    sample: auto
    slices: 5
    update_interval: null
    walks: 5
  updates:
    iterations_per_update: 500
    remove_state_files_at_end: true