GaussianPrior:
  lower_limit:
    type: Constant
    value: -inf
  upper_limit:
    type: Constant
    value: inf
centre:
  gaussian_limits:
    lower: -inf
    upper: inf
  lower_limit: 0.0
  type: Uniform
  upper_limit: 100.0
  width_modifier:
    type: Absolute
    value: 20.0
kurtosis:
  gaussian_limits:
    lower: -inf
    upper: inf
  lower_limit: 0.0
  type: Uniform
  upper_limit: 100.0
  width_modifier:
    type: Absolute
    value: 20.0
normalization:
  gaussian_limits:
    lower: 0.0
    upper: inf
  lower_limit: 1.0e-06
  type: LogUniform
  upper_limit: 1000000.0
  width_modifier:
    type: Relative
    value: 0.5
sigma:
  gaussian_limits:
    lower: 0.0
    upper: inf
  lower_limit: 0.0
  type: Uniform
  upper_limit: 25.0
  width_modifier:
    type: Relative
    value: 0.5
